<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>DahuaGrab</RootNamespace>
    <AssemblyName>DahuaGrab</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DahuaGrab.Tests" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="DIAVision.Core">
      <HintPath>..\..\references\DIAVision.Core.dll</HintPath>
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared\Enums\CameraSDK.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\references\Dahua\*.dll" Link="%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="DahuaGrab.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
